create service accounts
DataBiosphere/hamm pull request #9
Opened 2019-02-27 11:22 UTC by Qi77Qi

Create service account and give admin role for metadata topic to this service account using terraform

Even though we don't have terraform pipeline for this set up yet. I think it's better than creating service accounts manually. 
1. It'll be easier to roll out the changes
2. It's more visible what the changes will be than creating them manually.

2019-02-27 13:43 UTC, dvoet requested changes
before merging this I would like a discussion of how we use terraform and where this stuff should go and how we intend to run it

2019-02-27 15:07 UTC, RLuckom requested changes
Please use or create a repo like https://github.com/broadinstitute/terraform-sam-solo that uses our established patterns for running terraform, storing terraform state, and using credentials stored in vault.

2019-02-27 15:53 UTC, Qi77Qi commented
@RLuckom , this PR is for creating service accounts, I don't think it's the same as creating other resources. I think you said the terraform service account in ci doesn't have permission to manage service accounts, no?

2019-02-27 23:51 UTC, RLuckom commented
We may be having a miscommunication about this. I'm not trying to discourage you from using terraform locally to do this if that's how you want to create resources. I just don't want you to merge this, because I don't think this is a good approach to _sharing_ terraform code and I don't want it to set a precedent. 

I think the existing pattern in the repo I linked is a pretty good approach to sharing terraform code, and it also has the advantage that it's well-known by the devops team and used in many other places throughout the organization. The existing pattern solves three problems that always come up when a team uses terraform:

## Where does the state go?

If two people pull down this branch and run terraform against it, at least one of them will get an error, because this terraform config saves state locally. It is not good to check code into a shared repository unless there's a way for multiple people to use it.

## How do you deal with terraform upgrades?

When terraform runs against a stack whose state file was created by a lower version of terraform, the  newer version upgrades the state file, and older versions refuse to run against it. The existing pattern uses a terraform.sh script that runs a dockerized terraform so that the terraform version of the stack doesn't change unexpectedly. 

## What credentials should terraform run as? Where does terraform get secrets (like server certificates) from?

The existing pattern uses a pretty straightforward and scripted method of getting secrets (including the terraform service account) from vault and rendering templates to create the configs to be applied. That approach is totally automation-ready; if we decided to allow Jenkins to do it, we could easily make a job that did the exact same thing. In contrast, this PR relies on user credentials, which is a step _back_ from what we already have in terms of automation.

I don't mind having a conversation about whether we should add service account creation to the permissions we give the terraform role--maybe that's a good idea and we should do it. I'd also be happy to talk about any needs the existing process doesn't meet. But I'm not going to approve merging stuff that breaks the existing pattern without constructively addresses the needs that pattern was designed to fulfill.

2019-02-28 03:55 UTC, Qi77Qi commented
@RLuckom I'm not trying to diverge from existing terraform pattern. I'll thumb up if we decide to create service account in automation and make it happen. But right now, I just need some service accounts to unblock other work. If people don't want the code merged, that's fine. But I think it makes sense to use this outside automation create the service accounts for my purpose because the alternative is creating them in console.

2019-12-17 17:42 UTC, closed without merging